<a href="https://colab.research.google.com/github/JorgePeje/test-python-utec/blob/main/Programacion-Python-Utec/modulo2_estructurasdatossecuenciales/SESION18/%5B5%5D_Progama_Python_UTEC_Sesion06_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy

### [1] Crear un arreglo NumPy

In [2]:
# Llamar a la librería
import numpy as np

In [ ]:
# Crear un arreglo en numpy
arr_1 = np.array([2,4,6])

In [ ]:
# Visualizar el arreglo
print(f"El arreglo en numpy es \n{arr_1}")
type(arr_1)

El arreglo en numpy es 
[2 4 6]


numpy.ndarray

In [ ]:
lista_0= [2,4,6]
print(f"La lista es \n{lista_0}")

La lista es 
[2, 4, 6]


In [ ]:
# lista de listas
lista_1 = [[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]]
print(f'La Lista de listas es \n{lista_1}')

La Lista de listas es 
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [ ]:
arreglo_1 = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])
print(f"El arreglo es \n{arreglo_1}")
print(f"\nEl tipo de dato es {type(arreglo_1)}")

El arreglo es 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

El tipo de dato es <class 'numpy.ndarray'>


In [ ]:
# Crear una lista
lista_2 = [2,4,6]
print(f"La lista es \n{lista_2}")

La lista es 
[2, 4, 6]


In [ ]:
print(f"El objeto arr_1 es del tipo \n{type(arr_1)}")
print(f"\nEl objeto lista_1 es del tipo \n{type(lista_2)}")

El objeto arr_1 es del tipo 
<class 'numpy.ndarray'>

El objeto lista_1 es del tipo 
<class 'list'>


In [ ]:
# Operaciones listas
print(f"El valor mínimo de la lista \n{lista_1} es {min(lista_2)}")
print(f"\nEl valor máximo de la lista \n{lista_1} es {max(lista_2)}")
print(f"\nLa suma total de la lista \n{lista_1} es {sum(lista_2)}")
print(f'\nEl promedio de la lista \n{lista_1} es {sum(lista_2)/len(lista_2)}')

El valor mínimo de la lista 
[2, 4, 6] es 2

El valor máximo de la lista 
[2, 4, 6] es 6

La suma total de la lista 
[2, 4, 6] es 12

El promedio de la lista 
[2, 4, 6] es 4.0


In [ ]:
%whos

Variable   Type       Data/Info
-------------------------------
arr_1      ndarray    3: 3 elems, type `int64`, 24 bytes
lista_0    list       n=3
lista_1    list       n=3
lista_2    list       n=3
np         module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


In [ ]:
# El símbolo "+" permite concatenar listas
lista_1 + [5]

[2, 4, 6, 5]

In [ ]:
print(f"El arreglo en numpy es \n{arr_1}")
print(f"Suma del arreglo en numpy con 5 es \n{arr_1 + 5}")

El arreglo en numpy es 
[2 4 6]
Suma del arreglo en numpy con 5 es 
[ 7  9 11]


In [ ]:
print(lista_0)
print(arr_1)

[2, 4, 6]
[2 4 6]


In [ ]:
res_ = lista_0 + arr_1
print(f'El resultado es \n{res_}')
print(f'El tipo de dato es \n{type(res_)}')


El resultado es 
[ 4  8 12]
El tipo de dato es 
<class 'numpy.ndarray'>


In [ ]:
res_ = np.array(lista_0) + arr_1
print(f'El resultado es \n{res_}')
print(f'El tipo de dato es \n{type(res_)}')

El resultado es 
[ 4  8 12]
El tipo de dato es 
<class 'numpy.ndarray'>


In [ ]:
# Crear arreglos de numpy

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(f"El arreglo a1 es \n{a1}")
print(f"\nEl arreglo a2 es \n{a2}")

El arreglo a1 es 
[1 2 3]

El arreglo a2 es 
[4 5 6]


In [ ]:
print(f"El arreglo a1 es del tipo \n{type(a1)}")
print(f"\nEl arreglo a2 es del tipo \n{type(a2)}")

El arreglo a1 es del tipo 
<class 'numpy.ndarray'>

El arreglo a2 es del tipo 
<class 'numpy.ndarray'>


### Actividad N034

Crear un arreglo en NumPy a partir de la información de la siguiente tabla y nombrarlo como data_array

In [ ]:
from google.colab import files

# Subir archivo desde tu máquina local
uploaded = files.upload()

Saving data_arreglo.png to data_arreglo.png


In [88]:
from IPython.display import Image, display

# Mostrar la imagen en Colab
display(Image(filename='data_arreglo.png'))

FileNotFoundError: [Errno 2] No such file or directory: 'data_arreglo.png'

In [89]:
data_array = np.array([
    [35, 10, 1, 3500, 12000],
    [50, 25, 3, 6000, 30000],
    [23, 2, 0, 50, 1500],
    [42, 15, 2, 1000, 2800]])
print(f'El arreglo de las siguientes personas es \n{data_array}')

El arreglo de las siguientes personas es 
[[   35    10     1  3500 12000]
 [   50    25     3  6000 30000]
 [   23     2     0    50  1500]
 [   42    15     2  1000  2800]]


### [2] Características de un arreglo

In [ ]:
arreglo_1 = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])
print(arreglo_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
type(arreglo_1)

numpy.ndarray

In [ ]:
arreglo_1.ndim

2

In [ ]:
arreglo_1.shape

(3, 4)

In [ ]:
arreglo_1.size

12

In [ ]:
arreglo_1.dtype.name

'int64'

### Actividad N035

Obtenga las siguientes características del arreglo NumPy data_array: el número de dimensiones, tamaño de cada dimensión, el número de elementos.

In [ ]:
print(f'El numero de  dimesiones del arreglo es \n{data_array.ndim}')
print(f'El tamaño de cada de cada dimesiones del arreglo es \n{data_array.shape}')
print(f'La cantidad de elementos del arreglo es \n{data_array.size}')

El numero de  dimesiones del arreglo es 
2
El tamaño de cada de cada dimesiones del arreglo es 
(4, 5)
La cantidad de elementos del arreglo es 
20


In [ ]:
data_array.dtype.name

'int64'

### [3] Operaciones matemáticas con arreglos NumPy

In [ ]:
arreglo_2 = np.array( [11, 12, 13, 14])
arreglo_3 = np.array( [ 1, 2, 3, 4])

In [ ]:
# Suma de arreglos
arreglo_4 = arreglo_2 + arreglo_3
print(f"EL arreglo resultante es \n{arreglo_4}")

EL arreglo resultante es 
[12 14 16 18]


In [ ]:
arreglo_2 = np.array( [11, 12, 13, 14])
arreglo_3_ = np.array( [ 1, 2, 3, 4, 5])
# Suma de arreglos con diferente forma
arreglo_4 = arreglo_2 + arreglo_3_
print(f"EL arreglo resultante es \n{arreglo_4}")

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [ ]:
# Resta de arreglos
arreglo_5 = arreglo_2 - arreglo_3
print(f"EL arreglo resultante es \n{arreglo_5}")

EL arreglo resultante es 
[10 10 10 10]


In [ ]:
# Potencia de arreglos
print(f"El arreglo_3 es {arreglo_3}")
arreglo_3**2

El arreglo_3 es [1 2 3 4]


array([ 1,  4,  9, 16])

In [ ]:
# Transformación de un arreglo
np.cos(arreglo_3)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# Multiplicación de matrices

A1 = np.array([[1, 1],[0, 1]])
A2 = np.array([[2, 0],[3, 4]])

In [ ]:
A1.shape[1] == A2.shape[0]

True

In [ ]:
np.dot(A1,A2)

array([[5, 4],
       [3, 4]])

In [ ]:
# Operaciones matemáticas con los arreglos de numpy
arr_sum = a1 + a2
arr_prod = a1 * a2
print(a1)
print(a2)
print(f"La suma de los arreglos es \n{arr_sum}")
print(f"\nLa multiplicación de los arreglos es \n{arr_prod}")

[1 2 3]
[4 5 6]
La suma de los arreglos es 
[5 7 9]

La multiplicación de los arreglos es 
[ 4 10 18]


In [ ]:
#Actividad 36
matriz_A = np.array([[1,2,3], [3,2,1]])
matriz_B = np.array([[0,2], [1,-1], [0,1]])
print(f"La matriz A es \n{matriz_A} y su forma es \n{matriz_A.shape}")
print(f"\nLa matriz B es \n{matriz_B} y su forma es \n{matriz_B.shape}")
print(f"\nLa multiplicación de las matrices 'A.B' es \n{np.dot(matriz_A,matriz_B)}")
print(f"\nLa multiplicación de las matrices 'B.A' es \n{np.dot(matriz_B,matriz_A)}")

La matriz A es 
[[1 2 3]
 [3 2 1]] y su forma es 
(2, 3)

La matriz B es 
[[ 0  2]
 [ 1 -1]
 [ 0  1]] y su forma es 
(3, 2)

La multiplicación de las matrices 'A.B' es 
[[2 3]
 [2 5]]

La multiplicación de las matrices 'B.A' es 
[[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


In [ ]:
# Matrices de 2D
mat_4 = np.array([[1,2,3],[4,5,6]])
print(f"La matriz de 2D es \n{mat_4}")

La matriz de 2D es 
[[1 2 3]
 [4 5 6]]


In [ ]:
# Crear una lista de listas
ll_1 = [[10,20,30],[10,10,10]]
print(f"La lista de listas es \n{ll_1}")
print(f"\nEl objeto ll_1 es del tipo \n{type(ll_1)}")

La lista de listas es 
[[10, 20, 30], [10, 10, 10]]

El objeto ll_1 es del tipo 
<class 'list'>


In [ ]:
# Crear una matriz en numpy a partir de una lista

mat_6 = np.array(ll_1)
print(f"La matriz de 2D es \n{mat_6}")
print(f"\nEl objeto mat_6 es del tipo \n{type(mat_6)}")

La matriz de 2D es 
[[10 20 30]
 [10 10 10]]

El objeto mat_6 es del tipo 
<class 'numpy.ndarray'>


In [3]:
# Creamos una matriz 1D a parit de arange
mat_7 = np.arange(15)
print(f"La matriz 1D de numpy es \n{mat_7}")
print(f"\nEl objeto mat_7 es del tipo \n{type(mat_7)}")

La matriz 1D de numpy es 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

El objeto mat_7 es del tipo 
<class 'numpy.ndarray'>


In [4]:
# Crear una matriz 2D en numpy a partir de una matriz 1D
mat_8 = mat_7.reshape(3,5) #3 filas, 5 columnas
print(f"La matriz 2D de numpy es \n{mat_8}")
print(f"\nEl objeto mat_8 es del tipo \n{type(mat_8)}")

La matriz 2D de numpy es 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

El objeto mat_8 es del tipo 
<class 'numpy.ndarray'>


In [5]:
print(f"El número de dimensiones del objeto mat_8 es {mat_8.ndim}")
print(f"\nEl tamaño de las dimensiones del objeto mat_8 es {mat_8.shape}")
print(f"\nEl número de elementos del objeto mat_8 es {mat_8.size}")

El número de dimensiones del objeto mat_8 es 2

El tamaño de las dimensiones del objeto mat_8 es (3, 5)

El número de elementos del objeto mat_8 es 15


In [8]:
# Crear una matriz de ceros con determinadas dimensiones
#4filas y 3columnas
mat_9 = np.zeros((4,3))

In [9]:
# Las características de la matriz
print(f"La matriz mat_9 es \n{mat_9}")
print(f"\nEl objeto mat_9 es del tipo \n{type(mat_9)}")
print(f"\nEl número de dimensiones de la matriz mat_9 es {mat_9.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_9 es {mat_9.shape}")
print(f"\nEl número de elementos de la matriz mat_9 es {mat_9.size}")

La matriz mat_9 es 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

El objeto mat_9 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_9 es 2

El tamaño de las dimensiones de la matriz mat_9 es (4, 3)

El número de elementos de la matriz mat_9 es 12


In [19]:
prueba1 = np.zeros((2,3,4))
print(prueba1)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
# Crear una matriz de valores espaciados en un intervalo
mat_10 = np.linspace(50,60,20)
# Las características de la matriz
# 50 : Valor inicial
# 60: valor final
# 20 : total de elementos
print(f"La matriz mat_10 es \n{mat_10}")
print(f"\nEl objeto mat_10 es del tipo \n{type(mat_10)}")
print(f"\nEl número de dimensiones de la matriz mat_10 es {mat_10.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_10 es {mat_10.shape}")
print(f"\nEl número de elementos de la matriz mat_10 es {mat_10.size}")

La matriz mat_10 es 
[50.         50.52631579 51.05263158 51.57894737 52.10526316 52.63157895
 53.15789474 53.68421053 54.21052632 54.73684211 55.26315789 55.78947368
 56.31578947 56.84210526 57.36842105 57.89473684 58.42105263 58.94736842
 59.47368421 60.        ]

El objeto mat_10 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_10 es 1

El tamaño de las dimensiones de la matriz mat_10 es (20,)

El número de elementos de la matriz mat_10 es 20


In [11]:
l_0 = [30,32,40,50,65]
print(f"El objeto l_0 es {l_0}")
print(f"El objeto l_0 es del tipo {type(l_0)}")

El objeto l_0 es [30, 32, 40, 50, 65]
El objeto l_0 es del tipo <class 'list'>


In [13]:
mat_11 = np.array(l_0) # Convertir una lista en un arreglo numpy
print(f"El objeto mat_11 es {mat_11}")
print(f"El objeto mat_11 es del tipo {type(mat_11)}")

El objeto mat_11 es [30 32 40 50 65]
El objeto mat_11 es del tipo <class 'numpy.ndarray'>


In [14]:
# Las características de la matriz
print(f"La matriz mat_11 es \n{mat_11}")
print(f"\nEl objeto mat_11 es del tipo \n{type(mat_11)}")
print(f"\nEl número de dimensiones de la matriz mat_11 es {mat_11.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_11 es {mat_11.shape}")
print(f"\nEl número de elementos de la matriz mat_11 es {mat_11.size}")

La matriz mat_11 es 
[30 32 40 50 65]

El objeto mat_11 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_11 es 1

El tamaño de las dimensiones de la matriz mat_11 es (5,)

El número de elementos de la matriz mat_11 es 5


In [15]:
import numpy as np
mat_12 = np.arange(24).reshape(2,4,3)
# Las características de la matriz
print(f"La matriz mat_12 es \n{mat_12}")
print(f"\nEl objeto mat_12 es del tipo \n{type(mat_12)}")
print(f"\nEl número de dimensiones de la matriz mat_12 es {mat_12.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_12 es {mat_12.shape}")
print(f"\nEl número de elementos de la matriz mat_12 es {mat_12.size}")

La matriz mat_12 es 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

El objeto mat_12 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_12 es 3

El tamaño de las dimensiones de la matriz mat_12 es (2, 4, 3)

El número de elementos de la matriz mat_12 es 24


In [16]:
print(f"\nEl número de dimensiones de la matriz mat_12 es {mat_12.ndim}") # Matriz de 3D
# .ravel() ,e permite convertir una matriz de N dimensiones a unidimensional
print(f"\nLa matriz mat_12 se convierte con la función ravel en \n{mat_12.ravel()}")
mat_12 = mat_12.ravel() #esta linea si modifica el codigo


El número de dimensiones de la matriz mat_12 es 3

La matriz mat_12 se convierte con la función ravel en 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [17]:
print(f"\nEl número de dimensiones de la matriz mat_12 es {mat_12.ndim}")


El número de dimensiones de la matriz mat_12 es 1


In [20]:
# np.array(objeto) => objeto se convierte en numpy array
ll_x = [[57,21,48,0],[71,27,60,0],[111,51,96,0]]
print(f"La lista de listas es \n{ll_x}")

La lista de listas es 
[[57, 21, 48, 0], [71, 27, 60, 0], [111, 51, 96, 0]]


In [23]:
mat_13 = np.array(ll_x)
print(f"La matriz mat_13 es \n{mat_13}")

La matriz mat_13 es 
[[ 57  21  48   0]
 [ 71  27  60   0]
 [111  51  96   0]]


In [24]:
mat_13 = np.array([
    [  # Primera matriz
        [57, 21, 48, 0],
        [71, 27, 60, 0],
        [111, 51, 96, 0]
    ],
    [  # Segunda matriz
        [66, 16, 36, 18],
        [95, 22, 58, 29],
        [83, 20, 46, 23]
    ],
    [  # Tercera matriz
        [44, 34, 72, 44],
        [34, 32, 72, 34],
        [13, 25, 64, 13]
    ]
])

In [25]:
# Las características de la matriz
print(f"La matriz mat_13 es \n{mat_13}")
print(f"\nEl objeto mat_13 es del tipo \n{type(mat_13)}")
print(f"\nEl número de dimensiones de la matriz mat_13 es {mat_13.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_13 es {mat_13.shape}")
print(f"\nEl número de elementos de la matriz mat_13 es {mat_13.size}")

La matriz mat_13 es 
[[[ 57  21  48   0]
  [ 71  27  60   0]
  [111  51  96   0]]

 [[ 66  16  36  18]
  [ 95  22  58  29]
  [ 83  20  46  23]]

 [[ 44  34  72  44]
  [ 34  32  72  34]
  [ 13  25  64  13]]]

El objeto mat_13 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_13 es 3

El tamaño de las dimensiones de la matriz mat_13 es (3, 3, 4)

El número de elementos de la matriz mat_13 es 36


In [26]:
# Crear una matriz con la ayuda de numpy de 3D que tenga 6 matrices de 2 filas x 2 columnas
# Podemos usar la función arange() para generar los elementos de la matriz
mat_14 = np.arange(24).reshape(6,2,2)
# Las características de la matriz
print(f"La matriz mat_14 es \n{mat_14}")
print(f"\nEl objeto mat_14 es del tipo \n{type(mat_14)}")
print(f"\nEl número de dimensiones de la matriz mat_14 es {mat_14.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_14 es {mat_14.shape}")
print(f"\nEl número de elementos de la matriz mat_14 es {mat_14.size}")

La matriz mat_14 es 
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]

El objeto mat_14 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_14 es 3

El tamaño de las dimensiones de la matriz mat_14 es (6, 2, 2)

El número de elementos de la matriz mat_14 es 24


In [30]:
# Acceder a los elementos de una matriz 3D
print(mat_13)
print(f"\nLos elementos de la primera matriz mat_13 son \n{mat_13[0]}")
print(f"\nLos elementos de la segunda matriz mat_13 son \n{mat_13[1]}")
print(f"\nLos elementos de la tercera matriz mat_13 son \n{mat_13[2]}")

[[[ 57  21  48   0]
  [ 71  27  60   0]
  [111  51  96   0]]

 [[ 66  16  36  18]
  [ 95  22  58  29]
  [ 83  20  46  23]]

 [[ 44  34  72  44]
  [ 34  32  72  34]
  [ 13  25  64  13]]]

Los elementos de la primera matriz mat_13 son 
[[ 57  21  48   0]
 [ 71  27  60   0]
 [111  51  96   0]]

Los elementos de la segunda matriz mat_13 son 
[[66 16 36 18]
 [95 22 58 29]
 [83 20 46 23]]

Los elementos de la tercera matriz mat_13 son 
[[44 34 72 44]
 [34 32 72 34]
 [13 25 64 13]]


In [29]:
print(f"Los elementos de la primera fila y la primera matriz mat_13 son \n{mat_13[0][0]}")

Los elementos de la primera fila y la primera matriz mat_13 son 
[57 21 48  0]


In [31]:
print(f"Los elementos de la tercera fila de la segunda matriz mat_13 son \n{mat_13[1][2]}")

Los elementos de la tercera fila de la segunda matriz mat_13 son 
[83 20 46 23]


In [34]:
print(f"El primer elemento de la tercera fila de la segunda matriz mat_13 son \n{mat_13[1][2][0]}")

El primer elemento de la tercera fila de la segunda matriz mat_13 son 
83


In [43]:
print(f"El valor mínimo de la matriz mat_13 es {mat_13.min()}")
print(f"El valor máximo de la matriz mat_13 es {mat_13.max()}")
print(f"La suma de los elementos de la matriz mat_13 es {mat_13[2].sum()}")

El valor mínimo de la matriz mat_13 es 0
El valor máximo de la matriz mat_13 es 111
La suma de los elementos de la matriz mat_13 es 481


In [46]:
matriz_jorge = np.array ([
      [[1,2,3],
      [4,5,6],
      [7,8,9]],

      [[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]]
])
print(matriz_jorge)
print(matriz_jorge.sum())
print(f"El valor de la tercera fila de la segunda matriz es: {matriz_jorge[1][2]}")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
171
El valor de la tercera fila de la segunda matriz es: [16 17 18]


### Actividad N036

Crear los arreglos A y B, realice el cálculo de multiplicación de matrices (A.B) y de (B.A)

In [ ]:
from google.colab import files

# Subir archivo desde tu máquina local
uploaded = files.upload()

In [ ]:
from IPython.display import Image, display

# Mostrar la imagen en Colab
display(Image(filename='actividad36.png'))

### [4] Operaciones con arreglos

In [47]:
mat_15 = np.array([[3,1],[2,7]])
# Las características de la matriz mat_15
print(f"La matriz es \n{mat_15}")
print(f"\nEl objeto es del tipo \n{type(mat_15)}")
print(f"\nEl número de dimensiones de la matriz es {mat_15.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz es {mat_15.shape}")
print(f"\nEl número de elementos de la matriz es {mat_15.size}")

La matriz es 
[[3 1]
 [2 7]]

El objeto es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz es 2

El tamaño de las dimensiones de la matriz es (2, 2)

El número de elementos de la matriz es 4


In [48]:
mat_16 = np.array([[4,2],[5,7]])
# Las características de la matriz mat_16
print(f"La matriz es \n{mat_16}")
print(f"\nEl objeto es del tipo \n{type(mat_16)}")
print(f"\nEl número de dimensiones de la matriz es {mat_16.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz es {mat_16.shape}")
print(f"\nEl número de elementos de la matriz es {mat_16.size}")

La matriz es 
[[4 2]
 [5 7]]

El objeto es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz es 2

El tamaño de las dimensiones de la matriz es (2, 2)

El número de elementos de la matriz es 4


In [52]:
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
# Suma de matrices por método directo
mat_17 = mat_15 + mat_16
# Las características de la matriz mat_17
print(f"La matriz es \n{mat_17}")
print(f"\nEl objeto es del tipo \n{type(mat_17)}")
print(f"\nEl número de dimensiones de la matriz es {mat_17.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz es {mat_17.shape}")
print(f"\nEl número de elementos de la matriz es {mat_17.size}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]
La matriz es 
[[ 7  3]
 [ 7 14]]

El objeto es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz es 2

El tamaño de las dimensiones de la matriz es (2, 2)

El número de elementos de la matriz es 4


In [53]:
# Suma de matrices por método add
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la suma es \n{np.add(mat_15,mat_16)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la suma es 
[[ 7  3]
 [ 7 14]]


In [54]:
# Resta de matrices
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la resta es \n{mat_15-mat_16}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la resta es 
[[-1 -1]
 [-3  0]]


In [55]:
# Resta de matrices con método subtract
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la resta es \n{np.subtract(mat_15,mat_16)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la resta es 
[[-1 -1]
 [-3  0]]


In [56]:
# Multiplicar matrices (a nivel de posiciones)
#np.multiply es una multiplicacion de posiciones
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la multiplicación es \n{np.multiply(mat_15,mat_16)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la multiplicación es 
[[12  2]
 [10 49]]


In [57]:
# Multiplicar matrices
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_15.dot(mat_16)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la multiplicación es 
[[17 13]
 [43 53]]


In [59]:
mat_18 = np.array([[1,2],[3,4],[5,6]])
mat_19 = np.array([[1,2,3],[3,4,5]])

print(f"La matriz mat_18 es \n{mat_18}")
print(f"\nEl número de dimensiones de la matriz mat_18 es {mat_18.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_18 es {mat_18.shape}")

print(f"\nLa matriz mat_19 es \n{mat_19}")
print(f"\nEl número de dimensiones de la matriz mat_19 es {mat_19.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_19 es {mat_19.shape}")


La matriz mat_18 es 
[[1 2]
 [3 4]
 [5 6]]

El número de dimensiones de la matriz mat_18 es 2

El tamaño de las dimensiones de la matriz mat_18 es (3, 2)

La matriz mat_19 es 
[[1 2 3]
 [3 4 5]]

El número de dimensiones de la matriz mat_19 es 2

El tamaño de las dimensiones de la matriz mat_19 es (2, 3)


In [60]:
# Multiplicar matrices
print(f"La primera matriz es \n{mat_18}")
print(f"\nLa segunda matriz es \n{mat_19}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_18.dot(mat_19)}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_19.dot(mat_18)}")

La primera matriz es 
[[1 2]
 [3 4]
 [5 6]]

La segunda matriz es 
[[1 2 3]
 [3 4 5]]

La matriz resultado de la multiplicación es 
[[ 7 10 13]
 [15 22 29]
 [23 34 45]]

La matriz resultado de la multiplicación es 
[[22 28]
 [40 52]]


In [61]:
print(f"La primera matriz es \n{mat_18}")
print(f"\nLa segunda matriz es \n{mat_19}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_18+mat_19}")

La primera matriz es 
[[1 2]
 [3 4]
 [5 6]]

La segunda matriz es 
[[1 2 3]
 [3 4 5]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [62]:
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLas matrices concatenadas \n{np.concatenate([mat_15,mat_16],axis=0)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

Las matrices concatenadas 
[[3 1]
 [2 7]
 [4 2]
 [5 7]]


In [63]:
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLas matrices concatenadas \n{np.concatenate([mat_15,mat_16],axis=1)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

Las matrices concatenadas 
[[3 1 4 2]
 [2 7 5 7]]


In [64]:
# Multiplicar matrices
print(f"La primera matriz es \n{mat_19}")
print(f"\nLa segunda matriz es \n{mat_18}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_19.dot(mat_18)}")

La primera matriz es 
[[1 2 3]
 [3 4 5]]

La segunda matriz es 
[[1 2]
 [3 4]
 [5 6]]

La matriz resultado de la multiplicación es 
[[22 28]
 [40 52]]


In [68]:
# Arreglo original
arreglo_1 = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])
print(arreglo_1)
arreglo_1.shape


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(3, 4)

In [110]:
arreglo_1.ravel()
#Lleva la matriz a 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [111]:

arreglo_1.shape = (6,2)
print(arreglo_1)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [112]:
arreglo_1[2,1]

np.int64(5)

In [113]:
arreglo_1.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [ ]:
#LA TRANSPUESTA ES SOLO UN EJEMPLO VISUAL, LA MATRIZ SIGUE SIENDO DE 6X2 , no paso de 2x6

In [114]:
print(arreglo_1[2,1])

5


In [105]:
#Seleccionamos la fila 1 y la columna 2.
# [x,y] x: columnas // y: filas
print(arreglo_1[1,0])

2


In [107]:
#Seleccionamos la fila 1 y las 3 primeras columnas.
print(arreglo_1[ 0 , 0:3 ])
print(arreglo_1 [0:3 , 0])

[0 1]
[0 2 4]


In [108]:
#Seleccionamos la fila 1 y todas las columnas.
arreglo_1[ : ,  0 ]

array([ 0,  2,  4,  6,  8, 10])

In [87]:
#Seleccionamos todas las filas y la columna 2.
arreglo_1[ 1 , : ]

array([2, 3])

### Actividad N037

Seleccione del arreglo data_array la edad y los años de experiencia del primer y tercer registro


In [90]:
print(data_array)

[[   35    10     1  3500 12000]
 [   50    25     3  6000 30000]
 [   23     2     0    50  1500]
 [   42    15     2  1000  2800]]


In [116]:
print(f'Esta es la (edad, años experiencia) del primer registro {data_array[0, 0:2]}')
print(f'\nEsta es la (edad, años experiencia) del tercer registro {data_array[2, 0:2]}')

Esta es la (edad, años experiencia) del primer registro [35 10]

Esta es la (edad, años experiencia) del tercer registro [23  2]


In [126]:
type(data_array[0, 0:2])

numpy.ndarray

In [124]:
concataneado = np.concatenate([data_array[0, 0:2], data_array[2, 0:2]], axis=0)
print(concataneado)

[35 10 23  2]


In [128]:
concataneado = np.concatenate([data_array[0, 0:2], data_array[2, 0:2]], axis=0).reshape(2,2)
print(concataneado)

[[35 10]
 [23  2]]


### [5] Estadísticas en arreglos NumPy

In [129]:
a = np.array([1, 2, 3, 4])

print(a.mean())   # promedio
print(a.sum())    # suma total
print(a.max())    # valor máximo
print(a.min())    # valor mínimo


2.5
10
4
1


### Actividad N038

Del arreglo data_array, calcule los valores mínimo, máximos y promedios de todas las variables


In [135]:
print(data_array)
#Calculando para la variable: Edad
print(f" La edad minima es: {data_array[0:4,0].min()}")
print(f" La edad maxima es: {data_array[0:4,0].max()}")
print(f" El promedio de edad es: {data_array[0:4,0].mean()}")

#Calculando para la variable: Añoa de experiencia
print(f" \nLos años de experiencia minima es: {data_array[0:4,1].min()}")
print(f" Los años de experiencia es: {data_array[0:4,1].max()}")
print(f" Los años de experiencia promedio es: {data_array[0:4,1].mean()}")

#Calculando para la variable: Numero de hijos
print(f" Los numeros de hijos minima es: {data_array[0:4,2].min()}")
print(f" Los numeros de hijos  es: {data_array[0:4,2].max()}")
print(f" \nLos numeros de hijos promedio es: {data_array[0:4,2].mean()}")

#Calculando para la variable: Impuestos
print(f" El impuesto minimo es: {data_array[0:4,3].min()}")
print(f" El impuesto maximo es: {data_array[0:4,3].max()}")
print(f" \nEl impuesto promedio es: {data_array[0:4,3].mean()}")

#Calculando para la variable: Ingresos
print(f" El ingreso minimo es: {data_array[0:4,4].min()}")
print(f" El ingreso maximo es: {data_array[0:4,4].max()}")
print(f" \nEl ingreso promedio es: {data_array[0:4,4].mean()}")

[[   35    10     1  3500 12000]
 [   50    25     3  6000 30000]
 [   23     2     0    50  1500]
 [   42    15     2  1000  2800]]
 La edad minima es: 23
 La edad maxima es: 50
 El promedio de edad es: 37.5
 
Los años de experiencia minima es: 2
 Los años de experiencia es: 25
 Los años de experiencia promedio es: 13.0
 Los numeros de hijos minima es: 0
 Los numeros de hijos  es: 3
 
Los numeros de hijos promedio es: 1.5
 El impuesto minimo es: 50
 El impuesto maximo es: 6000
 
El impuesto promedio es: 2637.5
 El ingreso minimo es: 1500
 El ingreso maximo es: 30000
 
El ingreso promedio es: 11575.0


In [139]:
data_array.shape

(4, 5)

In [140]:
data_array.shape[1]

5

In [141]:
#Otra forma de realizar

for i in range(data_array.shape[1]):
  print(data_array[:,i].mean())

37.5
13.0
1.5
2637.5
11575.0


### [6] Comparación de listas y arreglos NumPy

In [143]:
import numpy as np

lista = list(range(1_000_000))
array = np.array(lista)

In [144]:
lista

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [145]:
array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [146]:
type(lista)

list

In [147]:
type(array)

numpy.ndarray

In [148]:
import time

start = time.time()
[ x*2 for x in lista ]
print("Lista:", time.time() - start)


Lista: 0.05936694145202637


In [149]:
import time

start = time.time()
array * 2
print("NumPy:", time.time() - start)

NumPy: 0.002985715866088867


### [7] Caso aplicado: Cálculo de la elasticidad precio

In [151]:
import pandas as pd

data = pd.read_csv("data_arroz.csv", encoding='latin-1')

In [154]:
data.head(3) #muestrame los primeros registros (2), 2 primeros registros
#data --> Dataframe de pandas

Sku  Semana  Precio  Demanda
0  ARROZ EXTRA  X 5 KG COSTEÑO  201709    18.9     2468
1  ARROZ EXTRA  X 5 KG COSTEÑO  201710    19.2     1746
2  ARROZ EXTRA  X 5 KG COSTEÑO  201711    20.7     3941

In [156]:
array_arroz = np.array(data.iloc[:,2:]) #Todas las filas y la columna desde las 2: hacia delante
print(array_arroz)

[[1.8900e+01 2.4680e+03]
 [1.9200e+01 1.7460e+03]
 [2.0700e+01 3.9410e+03]
 [1.8400e+01 4.2440e+03]
 [2.0400e+01 1.1699e+04]
 [2.4000e+01 1.7460e+03]
 [1.9600e+01 3.9410e+03]
 [1.8900e+01 4.2440e+03]
 [1.8500e+01 9.2310e+03]
 [1.8900e+01 1.0703e+04]
 [1.9100e+01 6.7510e+03]
 [1.7300e+01 1.1648e+04]
 [1.7400e+01 1.0219e+04]
 [1.8100e+01 1.3600e+04]
 [1.8300e+01 1.1005e+04]
 [1.7800e+01 9.1120e+03]
 [1.5600e+01 2.8216e+04]
 [1.7500e+01 1.4062e+04]
 [1.9200e+01 9.3040e+03]
 [1.9000e+01 9.3670e+03]
 [1.9200e+01 8.2840e+03]
 [1.4900e+01 3.1372e+04]
 [1.6800e+01 3.4870e+03]
 [1.9200e+01 4.8590e+03]
 [1.8900e+01 7.5030e+03]
 [1.6300e+01 2.4464e+04]
 [1.7400e+01 1.3449e+04]]


In [ ]:
X = array_arroz[:,0]
X

In [ ]:
print(f"Las estadísticas de los precios son \n Mínimo: {X.min()} \n Máximo: {X.max()} \n Promedio: {X.mean()}")

In [ ]:
y = array_arroz[:,1]
y

In [ ]:
print(f"Las estadísticas de la demanda semanal en unidades son \n Mínimo: {y.min()} \n Máximo: {y.max()} \n Promedio: {np.round(y.mean(),2)}")

In [ ]:
X_ = np.column_stack((np.ones(len(X)), X))
X_

In [ ]:
y = y.reshape(-1, 1)
y

In [ ]:
p1 = np.linalg.inv(np.dot(X_.transpose(),X_))
p2 = np.dot(X_.transpose(),y)
beta = np.dot(p1,p2)

In [ ]:
beta

In [ ]:
beta[1,:]

In [ ]:
elasticidad = beta[1,:] * (X.mean()/y.mean())

In [ ]:
elasticidad

### Actividad N039

Calcular la elasticidad precio de un yogurt de 1 Litro, considere la información del archivo yogurt1L.csv que registra los precios y la demanda de este producto en 20 semanas consecutivas.