<a href="https://colab.research.google.com/github/JorgePeje/test-python-utec/blob/main/Programacion-Python-Utec/modulo2_estructurasdatossecuenciales/TAREA/JORGE_PEJE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
# 1. Creacion de listas

#Lista de numeros pares del 1 al 100
lista_pares = [2*i for i in range (1,51)]
print(lista_pares)

#2da forma
lista_pares2 = list(range(2,101,2))
print(lista_pares2)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [20]:
# 2. Manipulacion de listas

#Agregando numeros
lista_pares = lista_pares + [102, 104, 106]
print(lista_pares)

#Eliminando numeros
del lista_pares[:5]
print(lista_pares)


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]
[12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]


In [22]:
# 3. Operaciones con listas

#Raiz cuadrada de los elementos de la lista_pares
resultante = [i**0.5 for i in lista_pares]
print(resultante)

[3.4641016151377544, 3.7416573867739413, 4.0, 4.242640687119285, 4.47213595499958, 4.69041575982343, 4.898979485566356, 5.0990195135927845, 5.291502622129181, 5.477225575051661, 5.656854249492381, 5.830951894845301, 6.0, 6.164414002968976, 6.324555320336759, 6.48074069840786, 6.6332495807108, 6.782329983125268, 6.928203230275509, 7.0710678118654755, 7.211102550927978, 7.3484692283495345, 7.483314773547883, 7.615773105863909, 7.745966692414834, 7.874007874011811, 8.0, 8.12403840463596, 8.246211251235321, 8.366600265340756, 8.48528137423857, 8.602325267042627, 8.717797887081348, 8.831760866327848, 8.94427190999916, 9.055385138137417, 9.16515138991168, 9.273618495495704, 9.38083151964686, 9.486832980505138, 9.591663046625438, 9.695359714832659, 9.797958971132712, 9.899494936611665, 10.0, 10.099504938362077, 10.198039027185569, 10.295630140987]


In [23]:
# 4. Desempaquetado de tuplas
# Tupla dada
tupla_x = ("alumno", "Pedro", 15)

# Desempaquetar en tres variables
x, y, z = tupla_x

# Imprimir el mensaje
print(f"El {x} {y} obtuvo la calificación de {z}")

El alumno Pedro obtuvo la calificación de 15


In [27]:
# 5. Iteración en diccionarios

#Diccionario dado
notas = {'Programacion': 15.9, 'Matematica': 15.1, 'Fisica':15.6}

for curso, nota in notas.items():
    print(f"Mis calificaciones en el curso de {curso} es {nota}")

Mis calificaciones en el curso de Programacion es 15.9
Mis calificaciones en el curso de Matematica es 15.1
Mis calificaciones en el curso de Fisica es 15.6


In [31]:
# 6. Matrices y funciones de NumPy

import numpy as np

#Creacion de arreglo 1D
matriz_1d = np.array(lista_pares[:16])

#Conversion a matriz 2D
matriz_2d = matriz_1d.reshape(4,4)
print(matriz_2d)

#Calculo de la suma de sus elementos
suma_matriz_2d = np.sum(matriz_2d)
print("La suma de los elementos de la matriz 'matriz_2d' es:" ,suma_matriz_2d)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]]
La suma de los elementos de la matriz 'matriz_2d' es: 432


In [35]:
# 7. Pandas

import pandas as pd

#Importar datos excel
from google.colab import drive
drive.mount('/gdrive')



Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [37]:
ruta = "/content/drive/MyDrive/Datos Python UTEC/"
dataset = "datosDemograficos.xlsx"

ruta+dataset

df = pd.read_excel(ruta+dataset)
df

Indicadores  Fecundidad  Mortalidad  TasaMortalidadxMil  EsperanzaVida  \
0           Puno       30108        9951                6.86          71.44   
1     San Martín       16074        4889                5.63          72.45   
2          Tacna        5605        1900                5.40          75.11   
3         Tumbes        3924        1209                4.94          74.96   
4        Ucayali        8872        3020                5.93          71.99   
5         Loreto       21701        5381                5.07          72.75   
6    MadreDeDios        2571         660                4.54          73.29   
7       Moquegua        2651        1085                5.86          76.59   
8          Pasco        6355        1715                5.54          72.52   
9          Piura       36609       10332                5.50          74.88   
10           Ica       13350        4262                5.29          77.64   
11         Junín       28870        8584                6.24          72.78   
12    LaLibertad       34020       10331                5.39          76.45   
13    Lambayeque       21332        7127                5.55          76.86   
14          Lima      163089       55201                5.40          77.87   
15     Cajamarca       28914        8450                5.50          73.94   
16        Callao       15584        5513                5.27          78.38   
17         Cusco       24385        9298                6.97          71.39   
18  Huancavelica       13324        2788                5.54          70.93   
19       Huánuco       18486        5234                 NaN          72.64   
20      Amazonas        8376        2630                6.19          71.56   
21        Áncash       21329        7155                6.15          74.77   
22      Apurímac        9752        3061                6.61          71.33   
23      Arequipa       20946        7675                5.80          77.06   
24      Ayacucho       15633        4181                5.91          71.91   

    EVSoloHombres  EVSoloMujeres  TasaMortalidadInfantilxMilNacidos  \
0           68.77          74.25                              26.82   
1           69.65          75.40                              17.53   
2           72.31          78.06                              11.77   
3           72.09          77.98                              11.46   
4           69.24          74.87                              21.07   
5           70.09          75.54                              21.80   
6           70.71          76.00                              19.44   
7           73.69          79.64                              11.77   
8           69.63          75.56                              19.12   
9           72.07          77.84                              16.89   
10          74.88          80.53                               9.14   
11          70.01          75.69                              16.21   
12          73.65          79.39                              12.97   
13          74.10          79.76                              15.36   
14          75.11          80.76                               9.04   
15          71.23          76.79                              16.19   
16          75.68          81.22                               7.81   
17          68.70          74.21                              26.62   
18          68.53          73.45                              26.81   
19          69.95          75.46                              20.00   
20          69.16          74.07                              20.29   
21          71.94          77.75                              16.23   
22          68.83          73.96                              18.94   
23          74.31          79.94                              11.77   
24          69.10          74.86                              19.55   

    CrecimientoNatural  
0                20157  
1                11185  
2                 3705  
3  